=== civictechmy/myds/registry/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "required": [
    "name",
    "type",
    "files"
  ],
  "properties": {
    "name": {
      "type": "string",
      "description": "The name of the component"
    },
    "type": {
      "type": "string",
      "enum": [
        "components:ui",
        "components:layout",
        "components:lib"
      ],
      "description": "The type of component"
    },
    "dependencies": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "description": "npm package dependencies"
    },
    "registryDependencies": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "description": "Other components from the registry"
    },
    "files": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "path",
          "content",
          "type"
        ],
        "properties": {
          "path": {
            "type": "string"
          },
          "content": {
            "type": "string"
          },
          "type": {
            "type": "string"
          }
        }
      },
      "description": "Component files"
    },
    "tailwind": {
      "type": "object",
      "properties": {
        "config": {
          "type": "object"
        }
      },
      "description": "Tailwind configuration"
    }
  }
}

=== civictechmy/myds/registry/styles/default/label.json
{
  "name": "label",
  "type": "components:ui",
  "dependencies": [
    "@radix-ui/react-slot",
    "class-variance-authority"
  ],
  "registryDependencies": [],
  "files": [
    {
      "path": "components/ui/label.tsx",
      "content": "import { Slot } from \"@radix-ui/react-slot\";\nimport { cva, VariantProps } from \"class-variance-authority\";\nimport React, { ComponentProps, ForwardRefExoticComponent } from \"react\";\n\nconst label_cva = cva(\n  [\n    \"inline-flex gap-1 text-txt-black-700\",\n    \"group-disabled:text-txt-black-disabled group-disabled:cursor-not-allowed group-disabled:shadow-none\",\n    \"peer-disabled:text-txt-black-disabled peer-disabled:cursor-not-allowed peer-disabled:shadow-none\",\n  ],\n  {\n    variants: {\n      size: {\n        small: \"text-body-sm\",\n        medium: \"text-body-md\",\n        large: \"text-body-lg\",\n      },\n    },\n    defaultVariants: {\n      size: \"medium\",\n    },\n  },\n);\n\ninterface LabelProps\n  extends ComponentProps<\"label\">,\n    VariantProps<typeof label_cva> {\n  asChild?: boolean;\n}\n\nconst Label: ForwardRefExoticComponent<LabelProps> = React.forwardRef(\n  ({ asChild, size, className, ...props }, ref) => {\n    const Comp = asChild ? Slot : \"label\";\n    return (\n      <Comp className={label_cva({ size, className })} ref={ref} {...props} />\n    );\n  },\n);\nLabel.displayName = \"Label\";\n\nexport { Label };\n",
      "type": "components:ui"
    }
  ],
  "tailwind": {
    "config": {
      "theme": {
        "extend": {
          "colors": {}
        }
      }
    }
  }
}

=== civictechmy/myds/registry/ui/styles/default/button.json
{
  "name": "button",
  "type": "components:ui",
  "dependencies": [
    "@radix-ui/react-slot",
    "class-variance-authority"
  ],
  "registryDependencies": [
    "utils"
  ],
  "files": [
    {
      "path": "components/ui/button.tsx",
      "content": "import React, {\n  ComponentProps,\n  createContext,\n  forwardRef,\n  ForwardRefExoticComponent,\n  ReactNode,\n  useContext,\n  LegacyRef,\n} from \"react\";\nimport { clx } from \"@/lib/utils\";\nimport { cva, VariantProps } from \"class-variance-authority\";\nimport { Slot } from \"@radix-ui/react-slot\";\n\n/*========================================================================================================================*/\n\n/**\n * Button component that supports various styles and sizes.\n *\n * @example\n * <Button variant=\"primary-fill\" size=\"medium\" onClick={() => alert('Button clicked!')}>\n *   Click Me\n * </Button>\n */\nconst button_cva = cva(\n  [\n    \"group flex select-none items-center gap-1.5 rounded-md w-fit\",\n    \"font-body font-medium outline-none transition disabled:cursor-not-allowed\",\n    \"text-center active:translate-y-[0.5px]\",\n    \"focus:ring focus:ring-fr-primary\",\n  ],\n  {\n    variants: {\n      variant: {\n        \"default-outline\": [\n          \"bg-bg-white border border-otl-gray-200 text-txt-black-700 shadow-button\",\n          \"hover:bg-bg-white-hover hover:border-otl-gray-300 hover:text-txt-black-900\",\n          \"disabled:bg-bg-white-disabled disabled:text-txt-black-disabled disabled:border-transparent\",\n        ],\n        \"default-ghost\": [\n          \"bg-transparent border border-transparent text-txt-black-700\",\n          \"hover:bg-bg-white-hover\",\n          \"disabled:bg-bg-white-disabled disabled:text-txt-black-disabled disabled:border-transparent\",\n        ],\n        \"danger-fill\": [\n          \"bg-danger-600 border border-danger-600 text-white shadow-button\",\n          \"hover:bg-danger-700\",\n          \"disabled:bg-bg-danger-disabled disabled:text-white-disabled disabled:border-bg-danger-disabled\",\n        ],\n        \"danger-outline\": [\n          \"bg-bg-white border border-otl-danger-200 text-txt-danger shadow-button\",\n          \"hover:bg-bg-danger-50\",\n          \"disabled:bg-bg-white-disabled disabled:text-txt-danger-disabled disabled:border-transparent\",\n        ],\n        \"danger-ghost\": [\n          \"bg-transparent border border-transparent text-txt-danger\",\n          \"hover:bg-bg-danger-50\",\n          \"disabled:bg-bg-white-disabled disabled:text-txt-danger-disabled disabled:border-transparent\",\n        ],\n        \"primary-fill\": [\n          \"bg-primary-600 border border-primary-600 text-white shadow-button\",\n          \"hover:bg-primary-700\",\n          \"disabled:bg-bg-primary-disabled disabled:text-white-disabled disabled:border-bg-primary-disabled\",\n        ],\n        \"primary-outline\": [\n          \"bg-bg-white border border-otl-primary-200 text-txt-primary shadow-button\",\n          \"hover:bg-bg-primary-50\",\n          \"disabled:bg-bg-white-disabled disabled:text-txt-primary-disabled disabled:border-transparent\",\n        ],\n        \"primary-ghost\": [\n          \"bg-transparent border border-transparent text-txt-primary\",\n          \"hover:bg-bg-primary-50\",\n          \"disabled:bg-bg-white-disabled disabled:text-txt-primary-disabled disabled:border-transparent\",\n        ],\n        unset: null,\n      },\n\n      size: {\n        small: \"py-1.5 px-2.5 text-body-sm\",\n        medium: \"py-2 px-3 text-body-md\",\n        large: \"py-2.5 px-4 text-body-lg\",\n      },\n\n      iconOnly: {\n        true: \"aspect-square rounded-md\",\n        false: \"\",\n      },\n    },\n    compoundVariants: [\n      {\n        iconOnly: true,\n        size: \"small\",\n        className: \"p-2\",\n      },\n      {\n        iconOnly: true,\n        size: \"medium\",\n        className: \"p-2.5\",\n      },\n      {\n        iconOnly: true,\n        size: \"large\",\n        className: \"p-3\",\n      },\n    ],\n    defaultVariants: {\n      variant: \"primary-fill\",\n      size: \"small\",\n      iconOnly: false,\n    },\n  },\n);\n\nexport interface ButtonProps\n  extends ComponentProps<\"button\">,\n    VariantProps<typeof button_cva> {\n  asChild?: boolean;\n  iconOnly?: boolean;\n}\n\nconst Button: ForwardRefExoticComponent<ButtonProps> = forwardRef(\n  (\n    {\n      className,\n      variant = \"primary-fill\",\n      size = \"small\",\n      children,\n      asChild = false,\n      iconOnly = false,\n      ...props\n    },\n    ref,\n  ) => {\n    const Comp = asChild ? Slot : \"button\";\n\n    return (\n      <ButtonContext.Provider value={{ variant, size }}>\n        <Comp\n          ref={ref}\n          className={clx(button_cva({ variant, size, className, iconOnly }))}\n          {...props}\n        >\n          {children}\n        </Comp>\n      </ButtonContext.Provider>\n    );\n  },\n);\nButton.displayName = \"Button\";\n\n/*========================================================================================================================*/\n\nconst ButtonContext = createContext<VariantProps<typeof button_cva>>({\n  variant: \"primary-fill\",\n  size: \"small\",\n  iconOnly: false,\n});\n\n/*========================================================================================================================*/\n\n/**\n * ButtonCounter component is a forward-ref exotic component that utilizes the ButtonContext\n * to apply variant and size styles to a span element.\n *\n * @param {ButtonCounterProps} props - The properties for the ButtonCounter component.\n * @param {React.Ref} ref - The ref to be forwarded to the span element.\n * @returns {JSX.Element} The rendered span element with applied styles and children.\n */\n\nconst button_counter_cva = cva(\n  [\n    \"flex aspect-square shrink-0 items-center justify-center\",\n    \"rounded-full px-1 leading-none bg-bg-primary-600 text-txt-white\",\n    \"group-disabled:bg-bg-white-disabled group-disabled:text-inherit\",\n  ],\n  {\n    variants: {\n      variant: {\n        \"primary-fill\": [\"bg-white text-primary-600\"],\n        \"danger-fill\": [\"bg-white text-danger-600\"],\n        \"default-outline\": \"\",\n        \"default-ghost\": \"\",\n        \"danger-outline\": \"\",\n        \"danger-ghost\": \"\",\n        \"primary-outline\": \"\",\n        \"primary-ghost\": \"\",\n        unset: \"\",\n      },\n      size: {\n        small: \"h-4.5 w-4.5 text-body-sm\",\n        medium: \"h-5 w-5 text-body-sm\",\n        large: \"h-6 w-6 text-base\",\n      },\n    },\n    defaultVariants: {\n      variant: \"primary-fill\",\n      size: \"small\",\n    },\n  },\n);\n\ninterface ButtonCounterProps {\n  children: ReactNode;\n  ref?: LegacyRef<HTMLSpanElement | null>;\n}\n\nconst ButtonCounter: ForwardRefExoticComponent<ButtonCounterProps> = forwardRef(\n  ({ children }, ref) => {\n    const { variant, size } = useContext(ButtonContext);\n\n    return (\n      <span ref={ref} className={clx(button_counter_cva({ variant, size }))}>\n        {children}\n      </span>\n    );\n  },\n);\n\nButtonCounter.displayName = \"ButtonCounter\";\n\n/*========================================================================================================================*/\n\n/**\n * `ButtonIcon` forwards a ref to its child and applies a class based on the button size.\n *\n * @component\n * @param {ButtonIconProps} props - The properties for the ButtonIcon component.\n * @param {React.ReactNode} props.children - The child element to which the ref will be forwarded.\n * @param {React.Ref} ref - The ref to be forwarded to the child element.\n * @returns {React.ReactElement} The cloned child element with the forwarded ref and applied class name.\n */\n\nconst button_icon_cva = cva(\n  \"block stroke-inherit text-inherit stroke-[1.5px] shrink-0\",\n  {\n    variants: {\n      size: {\n        small: \"h-4 w-4\",\n        medium: \"h-5 w-5\",\n        large: \"h-5 w-5\",\n      },\n    },\n    defaultVariants: {\n      size: \"small\",\n    },\n  },\n);\n\ninterface ButtonIconProps extends ComponentProps<\"div\"> {\n  children: React.ReactElement<any, string | React.JSXElementConstructor<any>>;\n}\n\nconst ButtonIcon: ForwardRefExoticComponent<ButtonIconProps> = forwardRef(\n  ({ children, className, ...props }, ref) => {\n    const { size } = useContext(ButtonContext);\n\n    return (\n      <Slot\n        ref={ref}\n        className={button_icon_cva({ size, className })}\n        {...props}\n      >\n        {children}\n      </Slot>\n    );\n  },\n);\n\nButtonIcon.displayName = \"ButtonIcon\";\n\nexport { Button, ButtonIcon, ButtonCounter, button_cva };\n",
      "type": "components:ui"
    }
  ],
  "tailwind": {
    "config": {
      "theme": {
        "extend": {
          "colors": {}
        }
      }
    }
  }
}

=== civictechmy/myds/registry/ui/styles/default/cookie-banner.json
{
  "name": "cookie-banner",
  "type": "components:ui",
  "dependencies": [
    "@radix-ui/react-dialog",
    "@radix-ui/react-slot",
    "class-variance-authority"
  ],
  "registryDependencies": [
    "button",
    "utils"
  ],
  "files": [
    {
      "path": "components/ui/cookie-banner.tsx",
      "content": "import React, {\n  ComponentProps,\n  createContext,\n  forwardRef,\n  ForwardRefExoticComponent,\n  FunctionComponent,\n  useContext,\n  useState,\n} from \"react\";\nimport { Button } from \"./button\";\nimport {\n  Dialog,\n  DialogContent,\n  DialogClose,\n  DialogDescription,\n  DialogTitle,\n  DialogPortal,\n} from \"@radix-ui/react-dialog\";\nimport { clx } from \"@/lib/utils\";\nimport { Slot } from \"@radix-ui/react-slot\";\nimport { cva } from \"class-variance-authority\";\nimport { CrossIcon } from \"@/components/ui/icons/cross\";\n\ninterface CookieBannerContextValue {\n  showPreferences: boolean;\n  setShowPreferences: (show: boolean) => void;\n}\n\nconst CookieBannerContext = createContext<CookieBannerContextValue>({\n  showPreferences: false,\n  setShowPreferences: () => {},\n});\n\ntype CookieBannerProps = ComponentProps<typeof Dialog> & {\n  className?: string;\n};\n\nconst cookie_content_cva = cva([\n  \"bg-bg-white p-4.5 shadow-card border-otl-gray-200 fixed bottom-0 right-0 z-30 max-w-[500px]\",\n  \"space-y-1 rounded-lg border transition-all outline-none\",\n  \"data-[state=open]:animate-in data-[state=open]:slide-in-from-bottom-full data-[state=open]:fade-in data-[state=open]:duration-400\",\n  \"data-[state=closed]:animate-out data-[state=closed]:slide-out-to-bottom-full data-[state=closed]:fade-out data-[state=closed]:duration-200\",\n  \"sm:mb-4 sm:mr-4 sm:p-6\",\n]);\n\nconst CookieBanner: FunctionComponent<CookieBannerProps> = ({\n  className,\n  children,\n  ...props\n}) => {\n  const [showPreferences, setShowPreferences] = useState(false);\n  const resetPreferences = () => setShowPreferences(false);\n\n  return (\n    <CookieBannerContext.Provider\n      value={{ showPreferences, setShowPreferences }}\n    >\n      <Dialog {...props}>\n        <DialogPortal>\n          <DialogContent\n            className={clx(cookie_content_cva(), className)}\n            onInteractOutside={resetPreferences}\n            {...props}\n          >\n            <DialogClose className=\"ring-fr-primary absolute right-0 top-0 mr-4 mt-4 rounded-md p-1.5 outline-none transition-all focus:ring\">\n              <CrossIcon className=\"size-4 shrink-0\" />\n            </DialogClose>\n            {children}\n          </DialogContent>\n        </DialogPortal>\n      </Dialog>\n    </CookieBannerContext.Provider>\n  );\n};\n\nconst cookie_action_cva = cva(\n  [\"w-full flex-col justify-start gap-[0.5rem] p-0 pt-3 sm:flex-row\"],\n  {\n    variants: {\n      showPreferences: {\n        true: \"flex\",\n        false: \"hidden\",\n      },\n    },\n    defaultVariants: {\n      showPreferences: false,\n    },\n  },\n);\n\nconst CookieBannerTitle: ForwardRefExoticComponent<\n  ComponentProps<typeof DialogTitle>\n> = forwardRef(({ className, ...props }, ref) => {\n  return (\n    <DialogTitle\n      ref={ref}\n      className={clx(\n        \"text-body-md font-body text-txt-black-900 font-semibold\",\n        className,\n      )}\n      {...props}\n    />\n  );\n});\nconst CookieBannerDescription: ForwardRefExoticComponent<\n  ComponentProps<typeof DialogDescription>\n> = forwardRef(({ className, ...props }, ref) => {\n  return (\n    <DialogDescription\n      ref={ref}\n      className={clx(\n        \"text-body-sm font-body text-txt-black-900 font-normal\",\n        className,\n      )}\n      {...props}\n    />\n  );\n});\n\nconst CookieBannerAction: ForwardRefExoticComponent<\n  ComponentProps<\"div\"> & { preferences?: boolean }\n> = forwardRef(({ className, preferences = false, ...props }, ref) => {\n  const context = useContext(CookieBannerContext);\n\n  if (!context)\n    throw new Error(\"CookieBannerAction must be used within CookieBanner\");\n\n  return (\n    <div\n      ref={ref}\n      className={clx(\n        cookie_action_cva({\n          showPreferences: context.showPreferences === preferences,\n        }),\n        className,\n      )}\n      {...props}\n    />\n  );\n});\n\nconst CookieBannerPreferences: ForwardRefExoticComponent<\n  ComponentProps<typeof DialogDescription>\n> = forwardRef(({ children, className, ...props }, ref) => {\n  const context = useContext(CookieBannerContext);\n\n  if (!context)\n    throw new Error(\"CookieBannerPreferences must be used within CookieBanner\");\n  if (!context.showPreferences) return null;\n\n  return (\n    <DialogDescription\n      ref={ref}\n      className={clx(\"flex flex-col gap-2 px-0 py-3\", className)}\n      {...props}\n    >\n      {children}\n    </DialogDescription>\n  );\n});\n\nconst CookieBannerPreferencesTrigger: ForwardRefExoticComponent<\n  ComponentProps<typeof Button>\n> = forwardRef(({ children, className, asChild = false, ...props }, ref) => {\n  const context = useContext(CookieBannerContext);\n  if (!context)\n    throw new Error(\n      \"CookieBannerPreferencesTrigger must be used within CookieBanner\",\n    );\n\n  const togglePreferences = () => {\n    context.setShowPreferences(!context.showPreferences);\n  };\n\n  const Comp = asChild ? Slot : Button;\n  return (\n    <Comp\n      variant=\"primary-outline\"\n      size=\"medium\"\n      className={clx(\"w-full justify-center sm:w-auto\", className)}\n      onClick={togglePreferences}\n      {...props}\n      ref={ref}\n    >\n      {children}\n    </Comp>\n  );\n});\n\nconst CookieBannerClose = DialogClose;\nCookieBanner.displayName = \"CookieBanner\";\nCookieBannerAction.displayName = \"CookieBannerAction\";\nCookieBannerDescription.displayName = \"CookieBannerDescription\";\nCookieBannerClose.displayName = \"CookieBannerClose\";\nCookieBannerPreferences.displayName = \"CookieBannerPreferences\";\nCookieBannerTitle.displayName = \"CookieBannerTitle\";\nCookieBannerPreferencesTrigger.displayName = \"CookieBannerPreferencesTrigger\";\n\nexport {\n  CookieBanner,\n  CookieBannerTitle,\n  CookieBannerDescription,\n  CookieBannerClose,\n  CookieBannerPreferences,\n  CookieBannerAction,\n  CookieBannerPreferencesTrigger,\n};\n",
      "type": "components:ui"
    }
  ],
  "tailwind": {
    "config": {
      "theme": {
        "extend": {
          "colors": {}
        }
      }
    }
  }
}

=== civictechmy/myds/registry/styles/default/announce-bar.json
{
  "name": "announce-bar",
  "type": "components:layout",
  "dependencies": [],
  "registryDependencies": [
    "tag",
    "utils"
  ],
  "files": [
    {
      "path": "components/ui/announce-bar.tsx",
      "content": "import { ComponentProps, forwardRef, ForwardRefExoticComponent } from \"react\";\nimport { clx } from \"@/lib/utils\";\nimport { Tag } from \"./tag\";\n\n/**\n * AnnounceBar component description.\n * @component\n * @example\n * <AnnounceBar>\n *   <AnnounceBarTag variant=\"warning\">\n *     Maintenance\n *   </AnnounceBarTag>\n *   <AnnounceBarDescription>\n *     <p>This service is undergoing maintenance. Thank you for your patience. <Link *underline=\"always\" primary href=\"#\">Send us your feedback here.</Link></p>\n *   </AnnounceBarDescription>\n * </AnnounceBar>\n */\n\ninterface AnnounceBarProps extends ComponentProps<\"div\"> {\n  border?: boolean;\n}\nconst AnnounceBar: ForwardRefExoticComponent<AnnounceBarProps> = forwardRef(\n  ({ className, children, border = true, ...props }, ref) => {\n    return (\n      <div\n        ref={ref}\n        className={clx(\n          \"mx-[18px] flex flex-row gap-2 py-2 md:mx-6\",\n          border && \"border-otl-gray-200 border-b\",\n          className,\n        )}\n        {...props}\n      >\n        {children}\n      </div>\n    );\n  },\n);\n\nconst AnnounceBarTag: typeof Tag = Tag;\n\nconst AnnounceBarDescription: ForwardRefExoticComponent<ComponentProps<\"div\">> =\n  forwardRef(({ children, className, ...props }, ref) => {\n    return (\n      <div\n        ref={ref}\n        className={clx(\n          \"min-height-[28px] text-txt-black-700 font-body flex items-center text-sm\",\n          className,\n        )}\n        {...props}\n      >\n        {children}\n      </div>\n    );\n  });\n\nexport { AnnounceBar, AnnounceBarTag, AnnounceBarDescription };\n",
      "type": "components:layout"
    }
  ],
  "tailwind": {
    "config": {
      "theme": {
        "extend": {
          "colors": {}
        }
      }
    }
  }
}

=== civictechmy/myds/registry/ui/styles/default/pill.json
{
  "name": "pill",
  "type": "components:ui",
  "dependencies": [
    "@radix-ui/react-slot",
    "class-variance-authority"
  ],
  "registryDependencies": [
    "button"
  ],
  "files": [
    {
      "path": "components/ui/pill.tsx",
      "content": "import { Slot, Slottable } from \"@radix-ui/react-slot\";\nimport { cva, VariantProps } from \"class-variance-authority\";\nimport React, { ComponentProps, ForwardRefExoticComponent } from \"react\";\nimport { CrossIcon } from \"@/components/ui/icons/cross\";\nimport { Button, ButtonIcon } from \"./button\";\n\nconst pill_cva = cva(\n  \"rounded-sm border font-medium text-txt-black-700 shadow-button inline-flex justify-between items-center\",\n  {\n    variants: {\n      size: {\n        small: \"px-[6px] py-[2px] text-body-xs gap-[2px]\",\n        medium: \"px-[8px] py-[4px] text-body-sm gap-[4px]\",\n        large: \"px-[10px] py-[4px] text-body-md gap-[4px]\",\n      },\n      disabled: {\n        false: \"border-otl-gray-300 bg-bg-dialog\",\n        true: \"border-otl-gray-200 bg-bg-white-disabled text-txt-black-disabled\",\n      },\n    },\n    defaultVariants: {\n      size: \"medium\",\n      disabled: false,\n    },\n  },\n);\n\ninterface PillProps\n  extends ComponentProps<\"div\">,\n    VariantProps<typeof pill_cva> {\n  asChild?: boolean;\n  disabled?: boolean;\n  onDismiss?: ComponentProps<typeof Button>[\"onClick\"];\n}\n\nexport const Pill: ForwardRefExoticComponent<PillProps> = React.forwardRef(\n  (\n    { asChild, children, disabled, size, className, onDismiss, ...props },\n    ref,\n  ) => {\n    const Comp = asChild ? Slot : \"div\";\n    return (\n      <Comp\n        className={pill_cva({ size, disabled, className })}\n        ref={ref}\n        {...props}\n      >\n        <Slottable>{children}</Slottable>\n        {onDismiss && !disabled && (\n          <Button\n            variant=\"default-ghost\"\n            size=\"small\"\n            className=\"p-0\"\n            onClick={onDismiss}\n          >\n            <ButtonIcon aria-label=\"close button\">\n              <CrossIcon className=\"text-txt-black-500 size-4\" />\n            </ButtonIcon>\n          </Button>\n        )}\n      </Comp>\n    );\n  },\n);\nPill.displayName = \"Pill\";\n",
      "type": "components:ui"
    }
  ],
  "tailwind": {
    "config": {
      "theme": {
        "extend": {
          "colors": {}
        }
      }
    }
  }
}

=== civictechmy/myds/registry/ui/styles/default/input.json
{
  "name": "input",
  "type": "components:ui",
  "dependencies": [
    "@radix-ui/react-slot",
    "class-variance-authority"
  ],
  "registryDependencies": [
    "utils"
  ],
  "files": [
    {
      "path": "components/ui/input.tsx",
      "content": "import {\n  Children,\n  ComponentProps,\n  ComponentPropsWithRef,\n  ForwardRefExoticComponent,\n  ReactNode,\n  createContext,\n  forwardRef,\n  isValidElement,\n  useContext,\n  useMemo,\n} from \"react\";\nimport { cva, VariantProps } from \"class-variance-authority\";\nimport { clx } from \"@/lib/utils\";\nimport { Slot } from \"@radix-ui/react-slot\";\n\ntype InputContextProps = {\n  size: \"small\" | \"medium\" | \"large\" | null;\n};\n\nconst InputContext = createContext<InputContextProps>({\n  size: \"small\",\n});\n\ninterface InputProps\n  extends Omit<ComponentProps<\"input\">, \"size\">,\n    VariantProps<typeof input_cva> {\n  prepend?: ReactNode;\n  append?: ReactNode;\n  children?: ReactNode;\n}\n\nconst input_cva = cva(\n  [\n    \"bg-bg-white border border-transparent outline-none box-border rounded-md\",\n    \"placeholder:text-txt-black-500 text-txt-black-700 transition-colors w-full\",\n    \"focus:ring focus:ring-fr-primary focus:border-otl-primary-300\",\n    \"disabled:bg-bg-washed disabled:cursor-not-allowed disabled:text-txt-black-disabled\",\n    \"data-[has-prepend=true]:rounded-l-none data-[has-append=true]:rounded-r-none\",\n    \"data-[has-left-icon=true]:pl-10 data-[has-right-icon=true]:pr-10\",\n  ],\n  {\n    variants: {\n      size: {\n        small: \"py-1.5 px-3 text-body-sm\",\n        medium: \"py-2 px-3 text-body-md\",\n        large: \"py-2.5 px-3.5 text-body-lg\",\n      },\n    },\n    defaultVariants: {\n      size: \"small\",\n    },\n  },\n);\n\nconst Input: ForwardRefExoticComponent<InputProps> = forwardRef(\n  ({ className, prepend, append, children, size = \"small\", ...props }, ref) => {\n    const has_icon = useMemo(() => {\n      if (!children) return { left: false, right: false };\n      const _children = Children.toArray(children);\n      return {\n        left: _children.some(\n          (child) =>\n            isValidElement<ComponentPropsWithRef<typeof InputIcon>>(child) &&\n            child.props.position === \"left\",\n        ),\n        right: _children.some(\n          (child) =>\n            isValidElement<ComponentPropsWithRef<typeof InputIcon>>(child) &&\n            child.props.position === \"right\",\n        ),\n      };\n    }, [children]);\n\n    return (\n      <div\n        className={clx(\n          \"border-otl-gray-200 relative rounded-md border outline-none\",\n          className,\n        )}\n      >\n        <div className=\"flex w-full flex-row\">\n          <InputContext.Provider value={{ size }}>\n            {prepend}\n            <div className=\"relative w-full\">\n              <input\n                ref={ref}\n                className={input_cva({ size })}\n                data-has-prepend={!!prepend}\n                data-has-append={!!append}\n                data-has-left-icon={has_icon.left}\n                data-has-right-icon={has_icon.right}\n                {...props}\n              />\n              {children}\n            </div>\n            {append}\n          </InputContext.Provider>\n        </div>\n      </div>\n    );\n  },\n);\nInput.displayName = \"Input\";\n\n/*========================================================================================================================*/\n\nconst input_addon_cva = cva(\n  [\n    \"flex items-center\",\n    \"border border-transparent outline-none box-border \",\n    \"[&:not(:last-child)]:border-r-otl-gray-200 [&:not(:first-child)]:border-l-otl-gray-200\",\n  ],\n  {\n    variants: {\n      size: {\n        small: \"py-1.5 px-3 text-body-sm\",\n        medium: \"py-2 px-3 text-body-md\",\n        large: \"py-2.5 px-3.5 text-body-md\",\n      },\n    },\n  },\n);\n\ninterface InputAddonProps extends ComponentProps<\"div\"> {\n  asChild?: boolean;\n}\n\nconst InputAddon: ForwardRefExoticComponent<InputAddonProps> = forwardRef(\n  ({ className, asChild = false, ...props }, ref) => {\n    const { size } = useContext(InputContext);\n    const Comp = asChild ? Slot : \"div\";\n\n    return (\n      <Comp\n        ref={ref}\n        className={input_addon_cva({ size, className })}\n        {...props}\n      />\n    );\n  },\n);\n\nInputAddon.displayName = \"InputAddon\";\n\n/*========================================================================================================================*/\n\nconst input_icon_cva = cva([\"absolute top-0 bottom-0 my-auto\"], {\n  variants: {\n    size: {\n      small: \"size-4.5\",\n      medium: \"size-5\",\n      large: \"size-6\",\n    },\n    position: {\n      left: \"left-3\",\n      right: \"right-3\",\n    },\n  },\n  defaultVariants: {\n    position: \"left\",\n  },\n});\n\ninterface InputIconProps extends ComponentProps<\"div\"> {\n  position: \"left\" | \"right\";\n}\n\nconst InputIcon: ForwardRefExoticComponent<InputIconProps> = forwardRef(\n  ({ className, position = \"left\", ...props }, ref) => {\n    const { size } = useContext(InputContext);\n\n    return (\n      <Slot\n        ref={ref}\n        className={input_icon_cva({ position, size, className })}\n        {...props}\n      />\n    );\n  },\n);\n\nInputIcon.displayName = \"InputIcon\";\n\n/*========================================================================================================================*/\n\nexport { Input, InputAddon, InputIcon };\n",
      "type": "components:ui"
    }
  ],
  "tailwind": {
    "config": {
      "theme": {
        "extend": {
          "colors": {}
        }
      }
    }
  }
}
