=== civictechmy/myds/registry/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "required": [
    "name",
    "type",
    "files"
  ],
  "properties": {
    "name": {
      "type": "string",
      "description": "The name of the component"
    },
    "type": {
      "type": "string",
      "enum": [
        "components:ui",
        "components:layout",
        "components:lib"
      ],
      "description": "The type of component"
    },
    "dependencies": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "description": "npm package dependencies"
    },
    "registryDependencies": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "description": "Other components from the registry"
    },
    "files": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "path",
          "content",
          "type"
        ],
        "properties": {
          "path": {
            "type": "string"
          },
          "content": {
            "type": "string"
          },
          "type": {
            "type": "string"
          }
        }
      },
      "description": "Component files"
    },
    "tailwind": {
      "type": "object",
      "properties": {
        "config": {
          "type": "object"
        }
      },
      "description": "Tailwind configuration"
    }
  }
}

=== civictechmy/myds/registry/ui/styles/default/date-field.json
{
  "name": "date-field",
  "type": "components:ui",
  "dependencies": [
    "class-variance-authority"
  ],
  "registryDependencies": [
    "calendar"
  ],
  "files": [
    {
      "path": "components/ui/date-field.tsx",
      "content": "import { ComponentProps, FunctionComponent } from \"react\";\nimport { CalendarIcon } from \"@/components/ui/icons/calendar\";\nimport { cva, VariantProps } from \"class-variance-authority\";\n\nconst datefield_container_cva = cva(\n  [\n    \"flex items-center gap-2 border rounded-md text-txt-black-900 shadow-button focus:outline-none font-body font-normal\",\n    \"focus-within:border-otl-primary-300 focus-within:ring focus-within:ring-fr-primary\",\n  ],\n  {\n    variants: {\n      size: {\n        small: \"px-[10px] py-[6px] text-sm\",\n        medium: \"px-[12px] py-[8px] text-base\",\n        large: \"px-[14px] py-[10px] text-lg\",\n      },\n      disabled: {\n        true: \"bg-bg-washed text-txt-black-500 cursor-not-allowed\",\n        false: \"bg-bg-white\",\n      },\n      invalid: {\n        true: \"border-otl-danger-300 ring-fr-danger ring\",\n        false: \"border-otl-gray-200\",\n      },\n    },\n    defaultVariants: {\n      size: \"small\",\n      disabled: false,\n    },\n  },\n);\n\nconst datefield_cva = cva([\n  \"bg-transparent focus:outline-none\",\n  \"disabled:bg-bg-washed disabled:text-txt-black-500 disabled:cursor-not-allowed\",\n  \"[&::-webkit-calendar-picker-indicator]:hidden\",\n  \"[&::-webkit-datetime-edit]:max-w-fit\",\n  \"[&::-webkit-datetime-edit-text]:mx-[2px]\",\n  \"[&::-webkit-datetime-edit-day-field:focus]:bg-primary-500 [&::-webkit-datetime-edit-day-field:focus]:text-txt-white\",\n  \"[&::-webkit-datetime-edit-month-field:focus]:bg-primary-500 [&::-webkit-datetime-edit-month-field:focus]:text-txt-white \",\n  \"[&::-webkit-datetime-edit-year-field:focus]:bg-primary-500 [&::-webkit-datetime-edit-year-field:focus]:text-txt-white\",\n]);\n\nconst icon_cva = cva([], {\n  variants: {\n    size: {\n      small: \"size-4\",\n      medium: \"size-4.5\",\n      large: \"size-5\",\n    },\n    disabled: {\n      true: \"text-txt-black-500\",\n      false: \"text-txt-black-700\",\n    },\n  },\n  defaultVariants: {\n    size: \"small\",\n    disabled: false,\n  },\n});\n\ntype DateFieldProps = Omit<ComponentProps<\"input\">, \"type\" | \"size\"> &\n  VariantProps<typeof datefield_container_cva>;\n\nconst DateField: FunctionComponent<DateFieldProps> = ({\n  className,\n  size,\n  disabled,\n  invalid,\n  ...props\n}) => {\n  return (\n    <div\n      className={datefield_container_cva({\n        size,\n        disabled,\n        invalid,\n        className,\n      })}\n    >\n      <label htmlFor=\"date-field\">\n        <CalendarIcon\n          className={icon_cva({ size, disabled })}\n          aria-label=\"Select date\"\n        />\n      </label>\n      <input\n        id=\"date-field\"\n        type=\"date\"\n        className={datefield_cva()}\n        disabled={disabled}\n        aria-invalid={invalid ?? undefined}\n        {...props}\n      />\n    </div>\n  );\n};\nDateField.displayName = \"DateField\";\n\nexport { DateField };\n",
      "type": "components:ui"
    }
  ],
  "tailwind": {
    "config": {
      "theme": {
        "extend": {
          "colors": {}
        }
      }
    }
  }
}

=== civictechmy/myds/registry/ui/styles/default/masthead.json
{
  "name": "masthead",
  "type": "components:layout",
  "dependencies": [
    "@radix-ui/react-collapsible",
    "@radix-ui/react-slot"
  ],
  "registryDependencies": [
    "malaysia-flag",
    "utils"
  ],
  "files": [
    {
      "path": "components/ui/masthead.tsx",
      "content": "import {\n  ComponentProps,\n  FunctionComponent,\n  ReactNode,\n  MouseEvent,\n} from \"react\";\nimport {\n  Collapsible,\n  CollapsibleTrigger,\n  CollapsibleContent,\n} from \"@radix-ui/react-collapsible\";\nimport { ChevronDownIcon } from \"@/components/ui/icons/chevron-down\";\nimport { MalaysiaFlagIcon } from \"@/components/ui/icons/malaysia-flag\";\nimport { clx } from \"@/lib/utils\";\nimport { Slot } from \"@radix-ui/react-slot\";\n\nconst Masthead: FunctionComponent<ComponentProps<\"div\">> = ({\n  children,\n  className,\n  ...props\n}) => {\n  // useEffect(() => {\n  //   const handleKeyDown = (event: KeyboardEvent) => {\n  //     const details = document.getElementById(\n  //       \"masthead\",\n  //     ) as HTMLDetailsElement | null;\n\n  //     if (\n  //       event.altKey &&\n  //       (event.metaKey || event.ctrlKey) &&\n  //       event.key === \"Enter\"\n  //     ) {\n  //       event.preventDefault();\n  //       if (details) {\n  //         details.open = !details.open;\n  //       }\n  //     }\n\n  //     if ((event.metaKey || event.ctrlKey) && event.key === \"k\") {\n  //       event.preventDefault();\n  //     }\n  //   };\n\n  //   document.addEventListener(\"keydown\", handleKeyDown);\n  //   return () => document.removeEventListener(\"keydown\", handleKeyDown);\n  // }, []);\n\n  return (\n    <Collapsible>\n      <div\n        id=\"masthead\"\n        className={clx(\"bg-bg-washed print:hidden\", className)}\n        data-nosnippet\n        {...props}\n      >\n        <div className=\"mx-auto grid w-full max-w-screen-xl outline-none transition-[grid-template-rows] duration-500 print:hidden\">\n          {children}\n        </div>\n      </div>\n    </Collapsible>\n  );\n};\n\nMasthead.displayName = \"Masthead\";\n\nconst MastheadHeader: FunctionComponent<ComponentProps<\"div\">> = ({\n  children,\n  ...props\n}) => {\n  return (\n    <div\n      className=\"px-4.5 flex items-center gap-2 overflow-x-hidden py-2 outline-none sm:py-1 md:px-6\"\n      {...props}\n    >\n      <MalaysiaFlagIcon className=\"inline-block aspect-auto w-fit shrink-0\" />\n      <div className=\"text-txt-black-700 text-body-sm flex w-full items-center justify-between truncate sm:justify-start\">\n        {children}\n      </div>\n    </div>\n  );\n};\n\nMastheadHeader.displayName = \"MastheadHeader\";\n\nconst MastheadTitle: FunctionComponent<ComponentProps<\"p\">> = ({\n  className,\n  ...props\n}) => {\n  return (\n    <p\n      className={clx(\n        \"text-txt-black-700 text-body-sm truncate sm:max-w-full sm:flex-grow-0\",\n        className,\n      )}\n      {...props}\n    />\n  );\n};\n\nMastheadTitle.displayName = \"MastheadTitle\";\n\nconst MastheadTrigger: FunctionComponent<ComponentProps<\"button\">> = ({\n  children,\n  onClick,\n  ...props\n}) => {\n  const handleToggle = (event: MouseEvent<HTMLButtonElement>) => {\n    if (onClick) onClick(event);\n  };\n\n  return (\n    <CollapsibleTrigger\n      className=\"text-txt-primary focus:ring-fr-primary bg-otl-gray-200 group flex items-center gap-0.5 rounded-md p-1 px-1 focus:outline-none focus:ring focus:ring-inset sm:bg-transparent sm:pl-1.5 xl:rounded-sm\"\n      aria-label=\"Toggle masthead\"\n      tabIndex={0}\n      onClick={handleToggle}\n      {...props}\n    >\n      <span className=\"text-txt-primary hidden select-none tracking-[-0.01em] sm:block\">\n        {children}\n      </span>\n      <ChevronDownIcon className=\"size-4 transform transition-transform group-data-[state=closed]:rotate-0 group-data-[state=open]:rotate-180\" />\n    </CollapsibleTrigger>\n  );\n};\n\nMastheadTrigger.displayName = \"MastheadTrigger\";\n\nconst MastheadContent: FunctionComponent<\n  ComponentProps<typeof CollapsibleContent>\n> = ({ children, className, ...props }) => {\n  return (\n    <CollapsibleContent\n      className={clx(\n        \"data-[state=open]:animate-collapsible-slide-down data-[state=closed]:animate-collapsible-slide-up overflow-hidden\",\n        \"motion-reduce:animate-none\",\n        className,\n      )}\n      {...props}\n    >\n      <div className=\"px-4.5 gap-4.5 flex flex-col pb-6 pt-3 sm:grid-cols-2 sm:flex-row sm:pb-8 sm:pt-6 md:px-6\">\n        {children}\n      </div>\n    </CollapsibleContent>\n  );\n};\n\nMastheadContent.displayName = \"MastheadContent\";\n\ninterface MastheadSectionProps extends ComponentProps<\"div\"> {\n  icon: ReactNode;\n  title: string;\n}\n\nconst MastheadSection: FunctionComponent<MastheadSectionProps> = ({\n  icon,\n  children,\n  title,\n  className,\n  ...props\n}) => {\n  return (\n    <div className={clx(\"flex w-full gap-3\", className)} {...props}>\n      <Slot className=\"text-txt-black-500 size-6 shrink-0\">{icon}</Slot>\n      <div className=\"space-y-1.5\">\n        <p className=\"text-txt-black-900 text-body-sm sm:text-body-md font-medium\">\n          {title}\n        </p>\n        <p className=\"text-txt-black-700 text-body-sm max-w-[50ch] text-balance\">\n          {children}\n        </p>\n      </div>\n    </div>\n  );\n};\n\nMastheadSection.displayName = \"MastheadSection\";\n\n// Exports\nexport {\n  Masthead,\n  MastheadHeader,\n  MastheadTitle,\n  MastheadTrigger,\n  MastheadContent,\n  MastheadSection,\n};\n",
      "type": "components:layout"
    }
  ],
  "tailwind": {
    "config": {
      "theme": {
        "extend": {
          "colors": {}
        }
      }
    }
  }
}

=== civictechmy/myds/registry/styles/default/summary-list.json
{
  "name": "summary-list",
  "type": "components:ui",
  "dependencies": [],
  "registryDependencies": [
    "utils"
  ],
  "files": [
    {
      "path": "components/ui/summary-list.tsx",
      "content": "import { ComponentProps, FunctionComponent } from \"react\";\nimport { clx } from \"@/lib/utils\";\n\nconst SummaryList: FunctionComponent<ComponentProps<\"div\">> = ({\n  children,\n  className,\n  ...props\n}) => (\n  <div className={clx(\"space-y-6\", className)} {...props}>\n    {children}\n  </div>\n);\n\nconst SummaryListHeader: FunctionComponent<ComponentProps<\"div\">> = ({\n  children,\n  className,\n  ...props\n}) => (\n  <h1\n    className={clx(\n      \"text-txt-black-900 text-xl font-semibold leading-[30px]\",\n      className,\n    )}\n    {...props}\n  >\n    {children}\n  </h1>\n);\n\nconst SummaryListBody: FunctionComponent<ComponentProps<\"table\">> = ({\n  children,\n  className,\n  ...props\n}) => (\n  <table\n    className={clx(\n      \"w-full text-sm font-medium\",\n      \"min-h-[40px]\",\n      \"relative\",\n      className,\n    )}\n    {...props}\n  >\n    <tbody>{children}</tbody>\n  </table>\n);\n\nconst SummaryListRow: FunctionComponent<ComponentProps<\"tr\">> = ({\n  children,\n  className,\n  ...props\n}) => (\n  <tr className={clx(\"border-otl-gray-200 border-b\", className)} {...props}>\n    {children}\n  </tr>\n);\n\nconst SummaryListTerm: FunctionComponent<ComponentProps<\"td\">> = ({\n  children,\n  className,\n  ...props\n}) => (\n  <th\n    // scope equals row here to indicate the header relates to all the row it belongs to\n    scope=\"row\"\n    className={clx(\n      \"text-txt-black-500 flex min-w-[190px] items-start py-3 pr-3\",\n      className,\n    )}\n    {...props}\n  >\n    {children}\n  </th>\n);\n\nconst SummaryListDetail: FunctionComponent<ComponentProps<\"td\">> = ({\n  children,\n  className,\n  ...props\n}) => (\n  <td\n    className={clx(\"text-txt-black-900 w-full py-3 pr-3\", className)}\n    {...props}\n  >\n    {children}\n  </td>\n);\n\nconst SummaryListAction: FunctionComponent<ComponentProps<\"td\">> = ({\n  children,\n  className,\n  ...props\n}) => (\n  <td\n    className={clx(\"flex justify-end py-1.5 pr-3 text-right\", className)}\n    {...props}\n  >\n    {children}\n  </td>\n);\n\nconst SummaryListAddition: FunctionComponent<ComponentProps<\"td\">> = ({\n  children,\n  className,\n  ...props\n}) => (\n  <td\n    className={clx(\"text-txt-black-900 min-w-36 py-2 pr-3\", className)}\n    {...props}\n  >\n    {children}\n  </td>\n);\n\nexport {\n  SummaryList,\n  SummaryListHeader,\n  SummaryListBody,\n  SummaryListRow,\n  SummaryListTerm,\n  SummaryListDetail,\n  SummaryListAction,\n  SummaryListAddition,\n};\n",
      "type": "components:ui"
    }
  ],
  "tailwind": {
    "config": {
      "theme": {
        "extend": {
          "colors": {}
        }
      }
    }
  }
}

=== civictechmy/myds/registry/styles/default/toggle.json
{
  "name": "toggle",
  "type": "components:ui",
  "dependencies": [
    "@radix-ui/react-toggle",
    "class-variance-authority"
  ],
  "registryDependencies": [
    "utils"
  ],
  "files": [
    {
      "path": "components/ui/toggle.tsx",
      "content": "import React, { createContext, useContext, useId } from \"react\";\nimport { cva, type VariantProps } from \"class-variance-authority\";\nimport { clx } from \"@/lib/utils\";\n\nconst thumbVariants = cva(\n  [\n    \"block outline-none focus:ring-[3px] focus:ring-fr-primary bg-otl-gray-200 hover:bg-otl-gray-300 data-[state=checked]:bg-bg-primary-600 cursor-pointer rounded-full transition-color duration-200 z-10\",\n    \"before:content-[''] before:left-[3px] before:bottom-[3px] before:bg-white before:absolute before:rounded-full before:transition-all before:duration-200\",\n    \"peer-disabled:data-[state=checked]:bg-bg-primary-disabled peer-disabled:cursor-not-allowed peer-disabled:before:data-[state=checked]:bg-bg-white\",\n    \"peer-disabled:data-[state=unchecked]:bg-bg-washed peer-disabled:before:data-[state=unchecked]:bg-bg-white\",\n  ],\n  {\n    variants: {\n      size: {\n        small:\n          \"h-[16px] w-[24px] before:size-[10px] before:data-[state=checked]:translate-x-2\",\n        medium:\n          \"h-[20px] w-[30px] before:size-[14px] before:data-[state=checked]:translate-x-[10px]\",\n        large:\n          \"h-[24px] w-[36px] before:size-[18px] before:data-[state=checked]:translate-x-3\",\n      },\n    },\n    defaultVariants: {\n      size: \"medium\",\n    },\n  },\n);\n\ninterface ToggleContextType extends VariantProps<typeof thumbVariants> {\n  checked: boolean;\n  disabled: boolean;\n  onChange: () => void;\n  id: string;\n}\n\nconst ToggleContext = createContext<ToggleContextType | undefined>(undefined);\n\nexport interface ToggleProps extends VariantProps<typeof thumbVariants> {\n  id?: string;\n  defaultChecked?: boolean;\n  checked?: boolean;\n  onCheckedChange?: (checked: boolean) => void;\n  disabled?: boolean;\n  className?: string;\n  children: React.ReactNode;\n}\n\nconst Toggle: React.FC<ToggleProps> = ({\n  id,\n  defaultChecked = false,\n  checked,\n  onCheckedChange,\n  size = \"medium\",\n  disabled = false,\n  className = \"\",\n  children,\n}) => {\n  const [_checked, set_checked] = React.useState(\n    checked || defaultChecked || false,\n  );\n\n  React.useEffect(() => {\n    if (checked === undefined) return;\n    set_checked(checked);\n  }, [checked]);\n\n  const handleChange = () => {\n    if (disabled) return;\n\n    set_checked(!_checked);\n    onCheckedChange?.(!_checked);\n  };\n\n  return (\n    <ToggleContext.Provider\n      value={{\n        checked: _checked,\n        disabled,\n        size,\n        onChange: handleChange,\n        id: id || useId(),\n      }}\n    >\n      <div\n        tabIndex={-1}\n        className={clx(\"flex items-start justify-between gap-2.5\", className)}\n      >\n        {children}\n      </div>\n    </ToggleContext.Provider>\n  );\n};\nToggle.displayName = \"Toggle\";\n\ninterface ToggleThumbProps {\n  className?: string;\n}\n\nconst ToggleThumb: React.FC<ToggleThumbProps> = ({ className }) => {\n  const context = useContext(ToggleContext);\n  if (!context) throw new Error(\"ToggleThumb must be used within Toggle\");\n\n  //* Handles keyboard interaction: Enter | Space\n  const handleKeyDown = (event: React.KeyboardEvent<HTMLSpanElement>) => {\n    if (event.key === \"Enter\" || event.key === \" \") {\n      event.preventDefault();\n      context.onChange();\n    }\n  };\n\n  return (\n    <label tabIndex={-1} className=\"relative inline-block\">\n      <input\n        id={context.id}\n        type=\"checkbox\"\n        className=\"peer sr-only\"\n        checked={context.checked}\n        onChange={context.onChange}\n        disabled={context.disabled}\n      />\n      <span\n        tabIndex={0}\n        role=\"switch\"\n        className={clx(thumbVariants({ size: context.size }), className)}\n        onKeyDown={handleKeyDown}\n        data-state={context.checked ? \"checked\" : \"unchecked\"}\n        aria-checked={context.checked}\n        aria-disabled={context.disabled}\n        aria-label=\"Toggle\"\n      />\n    </label>\n  );\n};\nToggleThumb.displayName = \"ToggleThumb\";\n\nexport { Toggle, ToggleThumb };\n",
      "type": "components:ui"
    }
  ],
  "tailwind": {
    "config": {
      "theme": {
        "extend": {
          "colors": {}
        }
      }
    }
  }
}

=== civictechmy/myds/registry/ui/styles/default/daterange-picker.json
{
  "name": "daterange-picker",
  "type": "components:ui",
  "dependencies": [
    "class-variance-authority",
    "date-fns",
    "react-day-picker"
  ],
  "registryDependencies": [
    "button",
    "calendar",
    "dialog",
    "hooks",
    "popover"
  ],
  "files": [
    {
      "path": "components/ui/daterange-picker.tsx",
      "content": "import { FC } from \"react\";\nimport { DateAfter, DateBefore, DateRange, Matcher } from \"react-day-picker\";\nimport { enGB, ms } from \"date-fns/locale\";\nimport { format } from \"date-fns\";\nimport { useControllableState } from \"@/components/ui/hooks\";\nimport { Button, button_cva } from \"./button\";\nimport { Calendar } from \"./calendar\";\nimport { Dialog, DialogBody, DialogContent, DialogTrigger } from \"./dialog\";\nimport { Popover, PopoverContent, PopoverTrigger } from \"./popover\";\nimport { VariantProps } from \"class-variance-authority\";\n\nexport type DateRangePickerProps = {\n  defaultValue?: DateRange;\n  disabled?: Matcher | Matcher[];\n  excludeDisabled?: boolean;\n  formatStr?: string;\n  fromLabel?: string;\n  locale?: \"en\" | \"ms\";\n  maxYear?: number;\n  minYear?: number;\n  onValueChange?: (date: DateRange) => void;\n  placeholder?: string;\n  value?: DateRange;\n  size?: VariantProps<typeof button_cva>[\"size\"];\n  toLabel?: string;\n  yearOrder?: \"asc\" | \"desc\";\n};\n\n/**\n * The DateRangePicker component allows users to select a range of dates from an interactive calendar.\n * @see {@link https://design.digital.gov.my/?path=/docs/myds-react-daterangepicker--docs}\n */\nconst DateRangePicker: FC<DateRangePickerProps> = ({\n  defaultValue,\n  disabled,\n  formatStr = \"dd MMM yyy\",\n  fromLabel,\n  locale = \"en\",\n  onValueChange,\n  placeholder = \"dd / mm / yyyy\",\n  value,\n  size,\n  toLabel,\n  ...props\n}) => {\n  const [selectedDateRange, setSelectedDateRange] = useControllableState({\n    prop: value,\n    onChange: onValueChange,\n    defaultProp: defaultValue,\n  });\n\n  const isMS = locale === \"ms\";\n  const _locale = isMS ? ms : enGB;\n  const formatDate = (date: Date) =>\n    format(date, formatStr, {\n      locale: _locale,\n    });\n\n  const dateBefore: DateBefore = {\n    // eslint-disable-next-line @typescript-eslint/no-non-null-asserted-optional-chain\n    before: selectedDateRange?.from!,\n  };\n  const dateAfter: DateAfter = {\n    // eslint-disable-next-line @typescript-eslint/no-non-null-asserted-optional-chain\n    after: selectedDateRange?.to!,\n  };\n\n  return (\n    <>\n      {/* Mobile */}\n      <div className=\"text-txt-black-900 flex items-center gap-1.5 lg:hidden\">\n        <Dialog>\n          <DialogTrigger asChild>\n            <Button\n              variant=\"default-outline\"\n              size={size}\n              className=\"whitespace-nowrap\"\n            >\n              <span className=\"text-txt-black-500\">\n                {fromLabel ? fromLabel : isMS ? \"Dari:\" : \"From:\"}\n              </span>\n              {selectedDateRange?.from\n                ? formatDate(selectedDateRange.from)\n                : placeholder}\n            </Button>\n          </DialogTrigger>\n          <DialogBody className=\"w-fit min-w-fit\" hideClose>\n            <DialogContent className=\"w-[304px] p-0\">\n              <Calendar\n                disabled={\n                  selectedDateRange?.to\n                    ? disabled\n                      ? Array.isArray(disabled)\n                        ? [...disabled, dateAfter]\n                        : [disabled, dateAfter]\n                      : dateAfter\n                    : disabled\n                }\n                locale={_locale}\n                mode=\"range\"\n                month={selectedDateRange?.from}\n                onSelect={({ from, to }) => {\n                  const date = from === selectedDateRange?.from ? to : from;\n                  setSelectedDateRange({ ...selectedDateRange, from: date });\n                }}\n                required\n                selected={selectedDateRange}\n                daterange=\"from\"\n                {...props}\n              />\n            </DialogContent>\n          </DialogBody>\n        </Dialog>\n        -\n        <Dialog>\n          <DialogTrigger asChild>\n            <Button\n              variant=\"default-outline\"\n              size={size}\n              className=\"whitespace-nowrap\"\n            >\n              <span className=\"text-txt-black-500\">\n                {toLabel ? toLabel : isMS ? \"Hingga:\" : \"To:\"}\n              </span>\n              {selectedDateRange?.to\n                ? formatDate(selectedDateRange.to)\n                : placeholder}\n            </Button>\n          </DialogTrigger>\n          <DialogBody className=\"w-fit min-w-fit\" hideClose>\n            <DialogContent className=\"w-[304px] p-0\">\n              <Calendar\n                disabled={\n                  selectedDateRange?.from\n                    ? disabled\n                      ? Array.isArray(disabled)\n                        ? [...disabled, dateBefore]\n                        : [disabled, dateBefore]\n                      : dateBefore\n                    : disabled\n                }\n                locale={_locale}\n                mode=\"range\"\n                month={selectedDateRange?.to}\n                onSelect={setSelectedDateRange}\n                required\n                selected={selectedDateRange}\n                daterange=\"to\"\n                {...props}\n              />\n            </DialogContent>\n          </DialogBody>\n        </Dialog>\n      </div>\n\n      {/* Desktop */}\n      <div className=\"text-txt-black-900 hidden items-center gap-1.5 lg:flex\">\n        <Popover>\n          <PopoverTrigger asChild>\n            <Button\n              variant=\"default-outline\"\n              size={size}\n              className=\"whitespace-nowrap\"\n            >\n              <span className=\"text-txt-black-500\">\n                {fromLabel ? fromLabel : isMS ? \"Dari:\" : \"From:\"}\n              </span>\n              {selectedDateRange?.from\n                ? formatDate(selectedDateRange.from)\n                : placeholder}\n            </Button>\n          </PopoverTrigger>\n          <PopoverContent className=\"w-[304px] p-0\" align=\"start\">\n            <Calendar\n              disabled={\n                selectedDateRange?.to\n                  ? disabled\n                    ? Array.isArray(disabled)\n                      ? [...disabled, dateAfter]\n                      : [disabled, dateAfter]\n                    : dateAfter\n                  : disabled\n              }\n              locale={_locale}\n              mode=\"range\"\n              month={selectedDateRange?.from}\n              onSelect={({ from, to }) => {\n                const date = from === selectedDateRange?.from ? to : from;\n                setSelectedDateRange({ ...selectedDateRange, from: date });\n              }}\n              required\n              selected={selectedDateRange}\n              daterange=\"from\"\n              {...props}\n            />\n          </PopoverContent>\n        </Popover>\n        -\n        <Popover>\n          <PopoverTrigger asChild>\n            <Button\n              variant=\"default-outline\"\n              size={size}\n              className=\"whitespace-nowrap\"\n            >\n              <span className=\"text-txt-black-500\">\n                {toLabel ? toLabel : isMS ? \"Hingga:\" : \"To:\"}\n              </span>\n              {selectedDateRange?.to\n                ? formatDate(selectedDateRange.to)\n                : placeholder}\n            </Button>\n          </PopoverTrigger>\n          <PopoverContent className=\"w-[304px] p-0\" align=\"end\">\n            <Calendar\n              disabled={\n                selectedDateRange?.from\n                  ? disabled\n                    ? Array.isArray(disabled)\n                      ? [...disabled, dateBefore]\n                      : [disabled, dateBefore]\n                    : dateBefore\n                  : disabled\n              }\n              locale={_locale}\n              mode=\"range\"\n              month={selectedDateRange?.to}\n              onSelect={setSelectedDateRange}\n              required\n              selected={selectedDateRange}\n              daterange=\"to\"\n              {...props}\n            />\n          </PopoverContent>\n        </Popover>\n      </div>\n    </>\n  );\n};\nDateRangePicker.displayName = \"DateRangePicker\";\n\nexport { DateRangePicker };\n\nexport type { DateRange };\n",
      "type": "components:ui"
    }
  ],
  "tailwind": {
    "config": {
      "theme": {
        "extend": {
          "colors": {}
        }
      }
    }
  }
}
